service:
  name: nest-sls-express-demo

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  profile: slsuser
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    BLOG_TABLE_NAME: ${self:custom.BlogTable.name}
  iamRoleStatements:
    - ${file(iam/BlogTableIAM.yml):BlogTableIAM}

functions:
  main: # The name of the lambda function
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+} # any+ ?

resources:
  Resources:
    BlogTable: ${file(resources/BlogTable.yml):BlogTable}

custom:
  BlogTable:
    name: !Ref BlogTable
    arn: !GetAtt BlogTable.Arn
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dotenv:
    logging: false
