BlogTable: # logical id of resource
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: BlogTable
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: createdAt
        AttributeType: S
      # - AttributeName: title
      #   AttributeType: S
      # - AttributeName: post
      #   AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: createdAt
        KeyType: RANGE
