import {
  attribute,
  hashKey,
  rangeKey,
  table,
  autoGeneratedHashKey,
} from '@aws/dynamodb-data-mapper-annotations';
// import { uuid } from 'uuidv4';

@table('BlogTable')
export class BlogModel {
  // @hashKey({ defaultProvider: () => uuid() })
  @autoGeneratedHashKey()
  id: string;

  @attribute()
  title: string;

  @attribute()
  post: string;
}
